import { useSession } from "next-auth/react";
import { ReactNode } from "react";
import SideMenu from "../SideMenu";
import Head from "next/head";

const Layout = ({ children }: { children: ReactNode }) => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>DupeX - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {session && <SideMenu />}
        {children}
      </main>
    </>
  );
};

export default Layout;
